### ISSUE TITLE
Viewing exposed metrics

### ISSUE THREAD

**Issue by jared1** [brightcove-archive/ooyala_metrics-storm#4]
After building the project successfully following the steps in the readme, I added the exported .jar to my storm classpath and enabled MetricsStormHooks in my storm.yaml file.

At this point, how do I view the exported metrics for my topologies? I tried connecting with JConsole to the default port of 7070 but am unable to see any of the exposed routes. Is there a configuration step I'm missing or more documentation that can be provided around this area?

Thanks

**Comment by velvia** [comment]
There is a config setting for a web port.  So if you go to each of your
worker nodes you should be able to use standard HTTP clients (eg curl) to
pull down the metrics.
The Yammer Metrics library is also able to automatically push stats to
various endpoints like Graphite, but there is no code to enable that right
now (though pretty easy to add).

-Evan

On Thu, Jan 9, 2014 at 12:16 PM, jared1 notifications@github.com wrote:

> After building the project successfully following the steps in the readme,
> I added the exported .jar to my storm classpath and enabled
> MetricsStormHooks in my storm.yaml file.
> 
> At this point, how do I view the exported metrics for my topologies? I
> tried connecting with JConsole to the default port of 7070 but am unable to
> see any of the exposed routes. Is there a configuration step I'm missing or
> more documentation that can be provided around this area?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ooyala/metrics_storm/issues/4
> .

## 

## 

Evan Chan
Staff Engineer
ev@ooyala.com  |

http://www.ooyala.com/
http://www.facebook.com/ooyalahttp://www.linkedin.com/company/ooyalahttp://www.twitter.com/ooyala

**Comment by jared1** [comment]
Thanks for the quick reply. I added the config setting for worker.webconsole.ports like below to my storm.yaml (I have four supervisor.slots.ports, so I supplied four web ports as directed in the readme):

worker.webconsole.ports:
    - 7000
    - 7001
    - 7002
    - 7003

Trying to execute, for example, "curl http://localhost:7000/metricz" though on my worker nodes, it's returning "curl: (52) Empty reply from server". Is there something I'm missing? The .jar I added to my storm classpath is the one from ~/.ivy2/local/default/metrics_storm_2.9.1/0.0.7-SNAPSHOT/jars after I executed "sbt publish-local". Examining that further, it looks like it's missing some of the dependencies like the Yammer Metrics library. Should I be including more than just that .jar on my classpath, or is there an additional step to package the needed dependencies?

Thanks for your help; I'm new to Scala and Storm so this has been a learning process for me.

-Jared

**Comment by velvia** [comment]
Hi Jared,

Ah. If you do "publish-local", yeah that does not publish the needed
dependencies.   What you probably need is an "assembly jar".
 Unfortunately our OSS repo doesn't have the plugin to do that, though it's
not hard to include it yourself.  See:
https://github.com/sbt/sbt-assembly

On Fri, Jan 10, 2014 at 8:31 AM, jared1 notifications@github.com wrote:

> Thanks for the quick reply. I added the config setting for
> worker.webconsole.ports like below to my storm.yaml (I have four
> supervisor.slots.ports, so I supplied four web ports as directed in the
> readme):
> 
> worker.webconsole.ports:
> - 7000
> - 7001
> - 7002
> - 7003
> 
> Trying to execute, for example, "curl http://localhost:7000/metricz"
> though on my worker nodes, it's returning "curl: (52) Empty reply from
> server". Is there something I'm missing? The .jar I added to my storm
> classpath is the one from
> ~/.ivy2/local/default/metrics_storm_2.9.1/0.0.7-SNAPSHOT/jars after I
> executed "sbt publish-local". Examining that further, it looks like it's
> missing some of the dependencies like the Yammer Metrics library. Should I
> be including more than just that .jar on my classpath, or is there an
> additional step to package the needed dependencies?
> 
> Thanks for your help; I'm new to Scala and Storm so this has been a
> learning process for me.
> 
> -Jared
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ooyala/metrics_storm/issues/4#issuecomment-32042240
> .

## 

## 

Evan Chan
Staff Engineer
ev@ooyala.com  |

http://www.ooyala.com/
http://www.facebook.com/ooyalahttp://www.linkedin.com/company/ooyalahttp://www.twitter.com/ooyala

**Comment by jared1** [comment]
Evan,

I was able to get everything successfully up-and-running after using sbt-assembly. I really appreciate your help and thanks for pointing me in the right direction with that link. Good stuff!

-Jared

**Comment by velvia** [comment]
Jared, you're welcome!

On Tue, Jan 21, 2014 at 12:12 PM, jared1 notifications@github.com wrote:

> Closed #4 https://github.com/ooyala/metrics_storm/issues/4.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ooyala/metrics_storm/issues/4
> .

## 

## 

Evan Chan
Staff Engineer
ev@ooyala.com  |

http://www.ooyala.com/
http://www.facebook.com/ooyalahttp://www.linkedin.com/company/ooyalahttp://www.twitter.com/ooyala

**Comment by codyaray** [comment]
Can you share the assembly.bt (and other files) you had to create to build the fat jar? I really don't know sbt (or even scala yet) and can't seem to make it work. I'm a java guy and, at this point, maven makes more sense than this "simple" build tool. ;)

At first I had dependency conflicts with server-api.jar, making it provided in build.sbt didn't fix it but I explicitly excluded the jar. Then all the project.clj files conflicted and when I tried to add the mergeStrategy like the sbt-assembly docs specify, I get an "error: not found: value PathList" error. I think I need to use MergeStrategy.concat but I'm not sure how to get around this issue PathList issue.

Help?

-Cody

**Comment by velvia** [comment]
Hey Cody,

Sorry, I think you should just stick with maven then.   All you need to do
is to run "sbt publish-local", which publishes a jar with a pom.xml in your
~/.ivy2/local/ dir, and you can include the pom.xml with your maven
project, I believe.

Of course we should just publish the jar to maven, but I'm not at ooyala
anymore, so can't really help with that.

-Evan

On Fri, Jun 6, 2014 at 2:24 PM, Cody A. Ray notifications@github.com
wrote:

> Can you share the assembly.bt (and other files) you had to create to
> build the fat jar? I really don't know sbt (or even scala yet) and can't
> seem to make it work. I'm a java guy and, at this point, maven makes more
> sense than this "simple" build tool. ;)
> 
> At first I had dependency conflicts with server-api.jar, making it
> provided in build.sbt didn't fix it but I explicitly excluded the jar. Then
> all the project.clj files conflicted and when I tried to add the
> mergeStrategy like the sbt-assembly docs specify, I get an "error: not
> found: value PathList" error. I think I need to use MergeStrategy.concat
> but I'm not sure how to get around this issue PathList issue.
> 
> Help?
> 
> -Cody
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ooyala/metrics_storm/issues/4#issuecomment-45385883.

## 

The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by codyaray** [comment]
I ended up figuring out how to build it (hint: had to update the
sbt.version to my current version in project/build.properties)... but I got
stuck somewhere else (which forget now) and ended up writing my own poller
to read stats from nimbus' thrift.

-Cody
